---

- name: create directory
  file: path=/srv/accounting/accounting-frontend state=directory

- name: copy files
  synchronize:
    src: "{{ item }}"
    dest: /srv/accounting/accounting-frontend/
  with_items:
    - ../index.html
    - ../dist
    - ../locales

- name: configure
  template:
    src: config.js.j2
    dest: '/srv/accounting/accounting-frontend/config.js'
